"""
One-heliostat train-size sensitivity experiment.

Sweeps over TRAIN_SIZES (e.g. [1, 5, 10, 20, 25, 50, 75, 100]) for a single
heliostat.  Each size runs a full train+eval cycle (same perturbed data, same
val/test split) so results are directly comparable.

Corrected pipeline: uses synthetic data pre-generated by
full_63_heli_kin_reconstruct/generate_dataset.py (data from perturbed scenario).
The KR starts from a clean scenario and must discover the perturbation values.
No separate data-generation step required.

Usage
-----
    python main.py
    python main.py --output-dir outputs/my_run
    python main.py --smoke-test
    python main.py --heliostat-id AA23
    python main.py --daic
"""
import argparse
import copy
import datetime
import gc
import json
import logging
import pathlib
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import h5py
import torch
from artist.scenario.scenario import Scenario
from artist.util import config_dictionary, set_logger_config
from artist.util.environment_setup import get_device, setup_distributed_environment
_here = pathlib.Path(__file__).resolve().parent
_src  = _here.parent
sys.path.insert(0, str(_src))

import config as cfg
from train import run
from utils.evaluation import build_heliostat_data_mapping
from utils.synth_data import _equalize_mapping, SyntheticDatasetParser
from utils.synth_reporting import plot_stage_convergence
from artist.data_parser.paint_calibration_parser import PaintCalibrationDataParser


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_mapping(split: str) -> list:
    return build_heliostat_data_mapping(
        benchmark_csv=cfg.BENCHMARK_CSV,
        calibration_properties_dir=cfg.CALIBRATION_PROPERTIES_DIR,
        flux_image_dir=cfg.FLUX_IMAGE_DIR,
        split=split,
    )


def _split_dir(split: str) -> pathlib.Path:
    return cfg.SYNTH_DATA_DIR / split


def _synth_split_has_heliostat(split: str, hid: str, n_samples: int) -> bool:
    hel_dir = _split_dir(split) / hid
    if not hel_dir.exists():
        return False
    return len(sorted(hel_dir.iterdir())) >= n_samples


def _run_reporting(
    results: dict,
    heliostat_ids: list,
    output_dir: pathlib.Path,
) -> None:
    for stage_name, filename, loss_label in [
        ("convergence_history_stage1.json", "convergence_stage1.png", "AlignmentLoss (rad²)"),
        ("convergence_history_stage2.json", "convergence_stage2.png", f"{results.get('loss_type', 'focal_spot')} Loss"),
    ]:
        history_file = output_dir / stage_name
        if history_file.exists():
            with open(history_file) as f:
                history = json.load(f)
            stage_label = "Stage 1 — AlignmentLoss" if "stage1" in stage_name else f"Stage 2 — {results.get('loss_type', 'focal_spot')}"
            plot_stage_convergence(
                history, output_dir,
                stage_name=stage_label,
                loss_label=loss_label,
                filename=filename,
            )


def _plot_convergence_overlay(
    train_sizes: list[int],
    run_dir: pathlib.Path,
    loss_type: str,
) -> None:
    """Overlay stage-2 val-loss convergence curves for all train sizes on one plot."""
    cmap = matplotlib.colormaps["plasma"].resampled(len(train_sizes))
    fig, ax = plt.subplots(figsize=(9, 5))
    fig.patch.set_facecolor("white")

    plotted = 0
    for i, n in enumerate(train_sizes):
        hist_file = run_dir / f"train_size_{n}" / "convergence_history_stage2.json"
        if not hist_file.exists():
            continue
        with open(hist_file) as f:
            history = json.load(f)
        epochs    = [e["epoch"]    for e in history]
        val_loss  = [e.get("eval_loss") for e in history]
        train_loss = [e.get("loss") for e in history]
        color = cmap(i)
        if any(v is not None for v in val_loss):
            vals = [v for v in val_loss if v is not None]
            eps  = [epochs[j] for j, v in enumerate(val_loss) if v is not None]
            ax.plot(eps, vals, color=color, linewidth=1.8, label=f"n={n}")
        elif train_loss:
            ax.plot(epochs, train_loss, color=color, linewidth=1.8, linestyle="--", label=f"n={n} (train)")
        plotted += 1

    if plotted == 0:
        plt.close(fig)
        return

    ax.set_xlabel("Epoch", fontsize=11)
    ax.set_ylabel("Stage-2 validation loss", fontsize=11)
    ax.set_title(f"Stage-2 convergence by train size — {loss_type}", fontsize=12)
    ax.legend(fontsize=9, ncol=2)
    ax.grid(True, alpha=0.35)
    fig.tight_layout()
    out = run_dir / "convergence_overlay.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)


def _plot_summary(summary: dict, output_dir: pathlib.Path) -> None:
    """Plot post-training mrad (val and test) vs train size."""
    sizes     = summary["train_sizes"]
    val_mrad  = [summary["results"][str(n)]["post_training"]["val"]["mean_mrad"]  for n in sizes]
    test_mrad = [summary["results"][str(n)]["post_training"]["test"]["mean_mrad"] for n in sizes]
    pre_test  = summary["results"][str(sizes[0])]["pre_training"]["test"]["mean_mrad"]

    fig, ax = plt.subplots(figsize=(8, 5))
    fig.patch.set_facecolor("white")
    ax.plot(sizes, val_mrad,  marker="o", color="steelblue",  linewidth=2, label="post-training val")
    ax.plot(sizes, test_mrad, marker="s", color="darkorange", linewidth=2, label="post-training test")
    ax.axhline(pre_test, color="tomato", linestyle="--", linewidth=1.2,
               label=f"pre-training test ({pre_test:.2f} mrad)")
    ax.set_xlabel("Training samples")
    ax.set_ylabel("Mean focal-spot error (mrad)")
    ax.set_title(f"Recovery vs training samples — heliostat {summary['heliostat_id']}")
    ax.legend()
    ax.grid(True, alpha=0.4)
    fig.tight_layout()
    fig.savefig(output_dir / "summary.png", dpi=150)
    plt.close(fig)


def _write_summary_table(summary: dict, output_dir: pathlib.Path) -> None:
    """Write a human-readable metrics table for all train sizes to summary_table.txt."""
    sizes = summary["train_sizes"]
    hid   = summary["heliostat_id"]
    lines = [
        f"One-heliostat train-size sensitivity — {hid}",
        f"Dataset: {summary['dataset_type']}   Loss: {summary['loss_type']}",
        "=" * 70,
        f"{'Size':>5} | {'Pre-train val':>13} {'Pre-train tst':>13} | {'Post-train val':>14} {'Post-train tst':>14}",
        f"{'':>5}-+-{'':-<13}-{'':-<13}-+-{'':-<14}-{'':-<14}",
    ]
    for n in sizes:
        r     = summary["results"][str(n)]
        pre_v = r["pre_training"]["val"]["mean_mrad"]
        pre_t = r["pre_training"]["test"]["mean_mrad"]
        trn_v = r["post_training"]["val"]["mean_mrad"]
        trn_t = r["post_training"]["test"]["mean_mrad"]
        lines.append(
            f"{n:5d} | {pre_v:13.4f} {pre_t:13.4f} | {trn_v:14.4f} {trn_t:14.4f}"
        )
    lines.append("")
    (output_dir / "summary_table.txt").write_text("\n".join(lines))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="One-heliostat train-size sensitivity experiment."
    )
    parser.add_argument("--output-dir", type=pathlib.Path, default=None)
    parser.add_argument(
        "--heliostat-id",
        default=None,
        help="Override config.HELIOSTAT_ID for this run.",
    )
    parser.add_argument(
        "--smoke-test",
        action="store_true",
        help="Run 5 epochs / 1 train ray on first 2 sizes only — quick end-to-end check.",
    )
    parser.add_argument("--daic", action="store_true", help="Use DAIC cluster paths.")
    args = parser.parse_args()

    if args.daic:
        cfg.IS_ON_DAIC = True
        cfg.BASE_DIR   = pathlib.Path("/home/nfs/agrigore/projects/githubProjects/master-thesis")
        cfg.PAINT_DIR  = pathlib.Path("/tudelft.net/staff-umbrella/StudentsCVlab/agrigore/datasets/paint")
        cfg.ONE_HELIOSTAT_SCENARIOS_DIR = cfg.BASE_DIR / "scenarios" / "one_heliostat_scenarios"
        cfg.SYNTH_DATA_DIR              = cfg.BASE_DIR / "scenarios" / "full_63_heli_kin_reconstruct" / "synthetic_data"
        cfg.BENCHMARK_CSV               = cfg.PAINT_DIR / "splits" / f"{cfg.BENCHMARK_NAME}.csv"
        cfg.CALIBRATION_PROPERTIES_DIR  = cfg.PAINT_DIR / cfg.BENCHMARK_NAME / "calibration_properties"
        cfg.FLUX_IMAGE_DIR              = cfg.PAINT_DIR / cfg.BENCHMARK_NAME / "flux_image"

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    if args.output_dir:
        run_dir = args.output_dir
    elif cfg.IS_ON_DAIC:
        run_dir = cfg.BASE_DIR / "outputs" / f"one_hel_train_sizes_{timestamp}"
    else:
        if args.smoke_test:
            run_dir = cfg.BASE_DIR / "outputs" / "local_runs" / "smoke_tests" / f"one_hel_{timestamp}"
        else:
            run_dir = cfg.BASE_DIR / "outputs" / "local_runs" / f"one_hel_train_sizes_{timestamp}"

    run_dir.mkdir(parents=True, exist_ok=True)

    set_logger_config()
    logging.getLogger().setLevel(logging.INFO)
    for _h in logging.getLogger().handlers:
        if isinstance(_h, logging.StreamHandler) and _h.stream is sys.stderr:
            _h.stream = sys.stdout
    log = logging.getLogger(__name__)

    fh = logging.FileHandler(run_dir / "run.log")
    fh.setFormatter(logging.Formatter("[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"))
    logging.getLogger().addHandler(fh)

    torch.manual_seed(0)
    device = get_device()
    log.info(f"Device: {device}")
    log.info(f"Output dir: {run_dir}")

    # ------------------------------------------------------------------ resolve heliostat ID
    # Each heliostat has its own single-heliostat scenario file, so we must know
    # the ID before loading the scenario (not after).
    heliostat_id = args.heliostat_id or cfg.HELIOSTAT_ID
    if not heliostat_id:
        log.error("No heliostat ID specified. Use --heliostat-id or set HELIOSTAT_ID in config.py.")
        sys.exit(1)
    log.info(f"Heliostat: {heliostat_id}")

    scenario_path = cfg.ONE_HELIOSTAT_SCENARIOS_DIR / heliostat_id / "scenario.h5"
    if not scenario_path.exists():
        log.error(
            f"Scenario not found for {heliostat_id}: {scenario_path}\n"
            f"Run: python one_heliostat_train_sizes/create_scenarios.py --heliostat-ids {heliostat_id}"
        )
        sys.exit(1)
    log.info(f"Scenario: {scenario_path}")

    heliostat_ids = [heliostat_id]

    # ------------------------------------------------------------------ perturbations
    # Perturbations are baked into the synthetic dataset; load ground-truth values
    # for recovery reporting only.  Never applied to the scenario at training time.
    perturbations_json_data = None
    if cfg.DATASET_TYPE == "synthetic":
        pert_path = cfg.SYNTH_DATA_DIR / "perturbations.json"
        if pert_path.exists():
            with open(pert_path) as f:
                all_perturbations = json.load(f)
            # Keep only the selected heliostat's entry.
            if heliostat_id in all_perturbations:
                perturbations_json_data = {heliostat_id: all_perturbations[heliostat_id]}
                log.info(f"Loaded perturbations for {heliostat_id} from {pert_path}")
            else:
                log.warning(f"Heliostat '{heliostat_id}' not found in perturbations.json — param recovery skipped.")
        else:
            log.warning(f"perturbations.json not found at {pert_path} — param recovery skipped.")

    # ------------------------------------------------------------------ data mappings
    log.info("Building data mappings …")
    max_train = max(cfg.TRAIN_SIZES)

    full_train_map = [
        e for e in _equalize_mapping(_build_mapping("train"), max_train)
        if e[0] == heliostat_id
    ]
    val_map = [
        e for e in _equalize_mapping(_build_mapping("validation"), cfg.VAL_SAMPLES)
        if e[0] == heliostat_id
    ]
    test_map = [
        e for e in _equalize_mapping(_build_mapping("test"), cfg.TEST_SAMPLES)
        if e[0] == heliostat_id
    ]
    log.info(
        f"Mappings — full_train: {len(full_train_map)}, val: {len(val_map)}, test: {len(test_map)}"
    )

    if not full_train_map:
        log.error(f"No training entries found for heliostat '{heliostat_id}'.")
        sys.exit(1)
    if not val_map or not test_map:
        log.error(f"No val/test entries found for heliostat '{heliostat_id}'.")
        sys.exit(1)

    # ------------------------------------------------------------------ synthetic data check
    if cfg.DATASET_TYPE == "synthetic":
        for split, n in [("val", cfg.VAL_SAMPLES), ("test", cfg.TEST_SAMPLES), ("train", max_train)]:
            min_ok = int(n * 0.90)
            if not _synth_split_has_heliostat(split, heliostat_id, min_ok):
                log.error(
                    f"Synthetic data missing for heliostat '{heliostat_id}' split='{split}' "
                    f"(expected ≥{min_ok} samples).\n"
                    f"Expected at: {_split_dir(split) / heliostat_id}\n"
                    "Run generate_dataset.py in full_field_200_samples first."
                )
                sys.exit(1)

    # ------------------------------------------------------------------ config snapshot
    _config_snapshot = {
        "heliostat_id":             heliostat_id,
        "benchmark_name":           cfg.BENCHMARK_NAME,
        "scenario_path":            str(scenario_path),
        "synth_data_dir":           str(cfg.SYNTH_DATA_DIR),
        "dataset_type":             cfg.DATASET_TYPE,
        "loss_type":                cfg.LOSS_TYPE,
        "stage1_epochs":            cfg.STAGE1_EPOCHS,
        "stage2_epochs":            cfg.STAGE2_EPOCHS,
        "train_sizes":              cfg.TRAIN_SIZES,
        "val_samples":              cfg.VAL_SAMPLES,
        "test_samples":             cfg.TEST_SAMPLES,
        "train_rays":               cfg.TRAIN_RAYS,
        "synth_gen_rays":           cfg.SYNTH_GEN_RAYS,
        "surface_points_per_facet": cfg.SURFACE_POINTS_PER_FACET,
        "optimization_config":      {str(k): v for k, v in cfg.OPTIMIZATION_CONFIG.items()},
        "smoke_test":               args.smoke_test,
        "output_dir":               str(run_dir),
        "pipeline":                 "corrected",
    }
    with open(run_dir / "config.json", "w") as f:
        json.dump(_config_snapshot, f, indent=2)

    # ------------------------------------------------------------------ smoke-test overrides
    train_sizes    = cfg.TRAIN_SIZES[:2] if args.smoke_test else cfg.TRAIN_SIZES
    optimization_config = cfg.OPTIMIZATION_CONFIG
    train_rays     = cfg.TRAIN_RAYS
    stage1_epochs  = cfg.STAGE1_EPOCHS
    stage2_epochs  = cfg.STAGE2_EPOCHS
    if args.smoke_test:
        stage1_epochs = 2
        stage2_epochs = 3
        train_rays    = 1
        log.info("SMOKE TEST: stage1=2, stage2=3, 1 ray, first 2 train sizes only.")

    n_groups = Scenario.get_number_of_heliostat_groups_from_hdf5(scenario_path)

    # ------------------------------------------------------------------ sweep
    all_results: dict[int, dict] = {}

    with setup_distributed_environment(
        number_of_heliostat_groups=n_groups, device=device
    ) as ddp_setup:
        device = ddp_setup[config_dictionary.device]

        for train_size in train_sizes:
            log.info(f"\n{'='*60}")
            log.info(f"Train size: {train_size} / {train_sizes}")
            log.info(f"{'='*60}")

            train_map = [(hid, cal[:train_size], flux[:train_size]) for hid, cal, flux in full_train_map]
            subdir    = run_dir / f"train_size_{train_size}"

            if cfg.DATASET_TYPE == "synthetic":
                train_parser = SyntheticDatasetParser(_split_dir("train"))
                val_parser   = SyntheticDatasetParser(_split_dir("val"))
                test_parser  = SyntheticDatasetParser(_split_dir("test"))
            else:
                train_parser = PaintCalibrationDataParser(
                    sample_limit=train_size,
                    centroid_extraction_method=cfg.CENTROID_METHOD,
                )
                val_parser = PaintCalibrationDataParser(
                    sample_limit=cfg.VAL_SAMPLES,
                    centroid_extraction_method=cfg.CENTROID_METHOD,
                )
                test_parser = PaintCalibrationDataParser(
                    sample_limit=cfg.TEST_SAMPLES,
                    centroid_extraction_method=cfg.CENTROID_METHOD,
                )

            results = run(
                scenario_path=scenario_path,
                device=device,
                ddp_setup=ddp_setup,
                train_mapping=train_map,
                val_mapping=val_map,
                test_mapping=test_map,
                train_parser=train_parser,
                val_parser=val_parser,
                test_parser=test_parser,
                optimization_config=optimization_config,
                output_dir=subdir,
                loss_type=cfg.LOSS_TYPE,
                dataset_type=cfg.DATASET_TYPE,
                n_surface_pts=cfg.SURFACE_POINTS_PER_FACET,
                train_rays=train_rays,
                perturbations_json=perturbations_json_data,
                heliostat_ids=[heliostat_id],
                stage1_epochs=stage1_epochs,
                stage2_epochs=stage2_epochs,
            )

            all_results[train_size] = results
            log.info(
                f"  train_size={train_size:3d} | "
                f"pre: val={results['pre_training']['val']['mean_mrad']:.3f}  "
                f"test={results['pre_training']['test']['mean_mrad']:.3f}  | "
                f"post: val={results['post_training']['val']['mean_mrad']:.3f}  "
                f"test={results['post_training']['test']['mean_mrad']:.3f} mrad  "
                f"({results['train_time_min']:.1f} min)"
            )

            _run_reporting(results, [heliostat_id], subdir)

            gc.collect()
            torch.cuda.empty_cache()

    # ------------------------------------------------------------------ convergence overlay
    _plot_convergence_overlay(train_sizes, run_dir, cfg.LOSS_TYPE)

    # ------------------------------------------------------------------ summary
    summary = {
        "heliostat_id": heliostat_id,
        "dataset_type": cfg.DATASET_TYPE,
        "loss_type":    cfg.LOSS_TYPE,
        "train_sizes":  train_sizes,
        "results":      {str(n): r for n, r in all_results.items()},
    }
    with open(run_dir / "summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    _plot_summary(summary, run_dir)
    _write_summary_table(summary, run_dir)

    log.info("\nAll sizes done:")
    log.info(f"  {'size':>5}  {'pre val':>8}  {'pre tst':>8}  {'post val':>9}  {'post tst':>9}")
    for n in train_sizes:
        r = all_results[n]
        log.info(
            f"  {n:5d}  "
            f"{r['pre_training']['val']['mean_mrad']:8.3f}  "
            f"{r['pre_training']['test']['mean_mrad']:8.3f}  "
            f"{r['post_training']['val']['mean_mrad']:9.3f}  "
            f"{r['post_training']['test']['mean_mrad']:9.3f}  mrad"
        )
    log.info(f"\nSummary table → {run_dir / 'summary_table.txt'}")
    log.info(f"Summary plot  → {run_dir / 'summary.png'}")
    log.info(f"Done. Results in: {run_dir}")


if __name__ == "__main__":
    main()
