"""
One-heliostat train-size sensitivity experiment.

Sweeps over TRAIN_SIZES (e.g. [1, 5, 10, 20, 25, 50, 75, 100]) for a single
heliostat.  Each size runs a full train+eval cycle (same perturbation, same
val/test data) so results are directly comparable.

Reuses synthetic data pre-generated by the full_field_200_samples experiment
— no separate data-generation step required.

Usage
-----
    python main.py
    python main.py --output-dir outputs/my_run
    python main.py --smoke-test
    python main.py --heliostat-id AA23
"""
import argparse
import copy
import datetime
import gc
import json
import logging
import pathlib
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import h5py
import torch
from artist.scenario.scenario import Scenario
from artist.util import config_dictionary, set_logger_config
from artist.util.environment_setup import get_device, setup_distributed_environment
from artist.data_parser.paint_calibration_parser import PaintCalibrationDataParser

_here = pathlib.Path(__file__).resolve().parent
_src  = _here.parent
sys.path.insert(0, str(_src))

import config as cfg
from train import run
from utils.evaluation import build_heliostat_data_mapping
from five_heliostats_synth.data import (
    _equalize_mapping,
    sample_perturbations,
    perturbations_to_json,
    SyntheticDatasetParser,
)
from five_heliostats_synth.reporting import (
    plot_convergence,
    plot_param_recovery,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_mapping(split: str) -> list:
    return build_heliostat_data_mapping(
        benchmark_csv=cfg.BENCHMARK_CSV,
        calibration_properties_dir=cfg.CALIBRATION_PROPERTIES_DIR,
        flux_image_dir=cfg.FLUX_IMAGE_DIR,
        split=split,
    )


def _split_dir(split: str) -> pathlib.Path:
    return cfg.SYNTH_DATA_DIR / split


def _synth_split_has_heliostat(split: str, hid: str, n_samples: int) -> bool:
    hel_dir = _split_dir(split) / hid
    if not hel_dir.exists():
        return False
    return len(sorted(hel_dir.iterdir())) >= n_samples


def _run_reporting(
    results: dict,
    perturbations_json: dict | None,
    heliostat_ids: list,
    output_dir: pathlib.Path,
) -> None:
    history_file = output_dir / "convergence_history.json"
    if history_file.exists():
        with open(history_file) as f:
            history = json.load(f)
        plot_convergence(
            history,
            output_dir,
            pre_perturbation_m=results["pre_perturbation"]["test"].get("mean_m"),
            post_perturbation_m=results["post_perturbation"]["test"].get("mean_m"),
            post_training_m=results["post_training"]["test"].get("mean_m"),
            pre_perturbation_mrad=results["pre_perturbation"]["test"].get("mean_mrad"),
            post_perturbation_mrad=results["post_perturbation"]["test"].get("mean_mrad"),
            post_training_mrad=results["post_training"]["test"].get("mean_mrad"),
        )

    if results.get("param_recovery"):
        plot_param_recovery(results["param_recovery"], output_dir)


def _plot_summary(summary: dict, output_dir: pathlib.Path) -> None:
    """Plot post-training mrad (val and test) vs train size."""
    sizes        = summary["train_sizes"]
    val_mrad     = [summary["results"][str(n)]["post_training"]["val"]["mean_mrad"]  for n in sizes]
    test_mrad    = [summary["results"][str(n)]["post_training"]["test"]["mean_mrad"] for n in sizes]
    perturb_val  = summary["results"][str(sizes[0])]["post_perturbation"]["val"]["mean_mrad"]
    perturb_test = summary["results"][str(sizes[0])]["post_perturbation"]["test"]["mean_mrad"]
    pre_val      = summary["results"][str(sizes[0])]["pre_perturbation"]["val"]["mean_mrad"]

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(sizes, val_mrad,  marker="o", color="steelblue",  linewidth=2, label="post-training val")
    ax.plot(sizes, test_mrad, marker="s", color="darkorange", linewidth=2, label="post-training test")
    ax.axhline(perturb_test, color="tomato",   linestyle="--", linewidth=1.2, label=f"post-perturbation test ({perturb_test:.2f} mrad)")
    ax.axhline(pre_val,      color="seagreen", linestyle="--", linewidth=1.2, label=f"pre-perturbation ({pre_val:.2f} mrad)")
    ax.set_xlabel("Training samples")
    ax.set_ylabel("Mean focal-spot error (mrad)")
    ax.set_title(f"Recovery vs training samples — heliostat {summary['heliostat_id']}")
    ax.legend()
    ax.grid(True, alpha=0.4)
    fig.tight_layout()
    fig.savefig(output_dir / "summary.png", dpi=150)
    plt.close(fig)


def _write_summary_table(summary: dict, output_dir: pathlib.Path) -> None:
    """Write a human-readable metrics table for all train sizes to summary_table.txt."""
    sizes = summary["train_sizes"]
    hid   = summary["heliostat_id"]
    lines = [
        f"One-heliostat train-size sensitivity — {hid}",
        f"Dataset: {summary['dataset_type']}   Loss: {summary['loss_type']}",
        "=" * 90,
        f"{'Size':>5} | {'Pre val':>8} {'Pre tst':>8} | {'Prtrb val':>10} {'Prtrb tst':>10} | {'Train val':>10} {'Train tst':>10}",
        f"{'':>5}-+-{'':-<8}-{'':-<8}-+-{'':-<10}-{'':-<10}-+-{'':-<10}-{'':-<10}",
    ]
    for n in sizes:
        r   = summary["results"][str(n)]
        pre_v  = r["pre_perturbation"]["val"]["mean_mrad"]
        pre_t  = r["pre_perturbation"]["test"]["mean_mrad"]
        pert_v = r["post_perturbation"]["val"]["mean_mrad"]
        pert_t = r["post_perturbation"]["test"]["mean_mrad"]
        trn_v  = r["post_training"]["val"]["mean_mrad"]
        trn_t  = r["post_training"]["test"]["mean_mrad"]
        lines.append(
            f"{n:5d} | {pre_v:8.4f} {pre_t:8.4f} | {pert_v:10.4f} {pert_t:10.4f} | {trn_v:10.4f} {trn_t:10.4f}"
        )
    lines.append("")
    (output_dir / "summary_table.txt").write_text("\n".join(lines))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="One-heliostat train-size sensitivity experiment."
    )
    parser.add_argument("--output-dir", type=pathlib.Path, default=None)
    parser.add_argument(
        "--heliostat-id",
        default=None,
        help="Override config.HELIOSTAT_ID for this run.",
    )
    parser.add_argument(
        "--smoke-test",
        action="store_true",
        help="Run 5 epochs / 1 train ray on first 2 sizes only — quick end-to-end check.",
    )
    args = parser.parse_args()

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    if args.output_dir:
        run_dir = args.output_dir
    elif cfg.IS_ON_DAIC:
        run_dir = cfg.BASE_DIR / "outputs" / f"one_hel_train_sizes_{timestamp}"
    else:
        suffix = "smoke" if args.smoke_test else f"one_hel_train_sizes_{timestamp}"
        run_dir = cfg.BASE_DIR / "outputs" / "local_runs" / suffix

    run_dir.mkdir(parents=True, exist_ok=True)

    set_logger_config()
    logging.getLogger().setLevel(logging.INFO)
    log = logging.getLogger(__name__)

    fh = logging.FileHandler(run_dir / "run.log")
    fh.setFormatter(logging.Formatter("[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"))
    logging.getLogger().addHandler(fh)

    torch.manual_seed(0)
    device = get_device()
    log.info(f"Device: {device}")
    log.info(f"Output dir: {run_dir}")

    # ------------------------------------------------------------------ load heliostat ID
    with h5py.File(cfg.SCENARIO_PATH, "r") as f:
        tmp = Scenario.load_scenario_from_hdf5(
            scenario_file=f,
            device=device,
            number_of_surface_points_per_facet=torch.tensor(
                [cfg.SURFACE_POINTS_PER_FACET, cfg.SURFACE_POINTS_PER_FACET]
            ),
        )
    heliostat_ids = list(tmp.heliostat_field.heliostat_groups[0].names)
    del tmp
    gc.collect()

    # Resolve final heliostat ID: CLI flag > config > first in scenario
    heliostat_id = args.heliostat_id or cfg.HELIOSTAT_ID or heliostat_ids[0]
    if heliostat_id not in heliostat_ids:
        log.error(f"Heliostat '{heliostat_id}' not in scenario (has: {heliostat_ids}).")
        sys.exit(1)
    log.info(f"Heliostat: {heliostat_id}")

    # ------------------------------------------------------------------ perturbations
    if cfg.DATASET_TYPE == "synthetic":
        perturbations = sample_perturbations(
            n_heliostats=1,
            ranges=cfg.PERTURBATION_RANGES,
            seed=cfg.PERTURBATION_SEED,
        )
        perturbations_json_data = perturbations_to_json(perturbations, [heliostat_id])
        with open(run_dir / "perturbations.json", "w") as f:
            json.dump(perturbations_json_data, f, indent=2)
        log.info("Perturbations sampled (n=1 heliostat, seed=%d).", cfg.PERTURBATION_SEED)
    else:
        perturbations = None
        perturbations_json_data = None
        log.info("Real dataset — skipping kinematic perturbations.")

    # ------------------------------------------------------------------ data mappings
    log.info("Building data mappings …")
    max_train = max(cfg.TRAIN_SIZES)

    full_train_map = [
        e for e in _equalize_mapping(_build_mapping("train"), max_train)
        if e[0] == heliostat_id
    ]
    val_map = [
        e for e in _equalize_mapping(_build_mapping("validation"), cfg.VAL_SAMPLES)
        if e[0] == heliostat_id
    ]
    test_map = [
        e for e in _equalize_mapping(_build_mapping("test"), cfg.TEST_SAMPLES)
        if e[0] == heliostat_id
    ]
    log.info(
        f"Mappings — full_train: {len(full_train_map)}, val: {len(val_map)}, test: {len(test_map)}"
    )

    if not full_train_map:
        log.error(f"No training entries found for heliostat '{heliostat_id}'.")
        sys.exit(1)
    if not val_map or not test_map:
        log.error(f"No val/test entries found for heliostat '{heliostat_id}'.")
        sys.exit(1)

    # ------------------------------------------------------------------ synthetic data check
    if cfg.DATASET_TYPE == "synthetic":
        for split, n in [("val", cfg.VAL_SAMPLES), ("test", cfg.TEST_SAMPLES), ("train", max_train)]:
            min_ok = int(n * 0.90)
            if not _synth_split_has_heliostat(split, heliostat_id, min_ok):
                log.error(
                    f"Synthetic data missing for heliostat '{heliostat_id}' split='{split}' "
                    f"(expected ≥{min_ok} samples).\n"
                    f"Expected at: {_split_dir(split) / heliostat_id}\n"
                    "Run generate_dataset.py in full_field_200_samples first."
                )
                sys.exit(1)

    # ------------------------------------------------------------------ config snapshot
    _config_snapshot = {
        "heliostat_id":             heliostat_id,
        "benchmark_name":           cfg.BENCHMARK_NAME,
        "scenario_path":            str(cfg.SCENARIO_PATH),
        "synth_data_dir":           str(cfg.SYNTH_DATA_DIR),
        "dataset_type":             cfg.DATASET_TYPE,
        "loss_type":                cfg.LOSS_TYPE,
        "train_sizes":              cfg.TRAIN_SIZES,
        "val_samples":              cfg.VAL_SAMPLES,
        "test_samples":             cfg.TEST_SAMPLES,
        "train_rays":               cfg.TRAIN_RAYS,
        "synth_gen_rays":           cfg.SYNTH_GEN_RAYS,
        "surface_points_per_facet": cfg.SURFACE_POINTS_PER_FACET,
        "perturbation_seed":        cfg.PERTURBATION_SEED,
        "perturbation_ranges":      cfg.PERTURBATION_RANGES,
        "optimization_config":      {str(k): v for k, v in cfg.OPTIMIZATION_CONFIG.items()},
        "smoke_test":               args.smoke_test,
        "output_dir":               str(run_dir),
    }
    with open(run_dir / "config.json", "w") as f:
        json.dump(_config_snapshot, f, indent=2)

    # ------------------------------------------------------------------ smoke-test overrides
    train_sizes = cfg.TRAIN_SIZES[:2] if args.smoke_test else cfg.TRAIN_SIZES
    optimization_config = cfg.OPTIMIZATION_CONFIG
    train_rays = cfg.TRAIN_RAYS
    if args.smoke_test:
        optimization_config = copy.deepcopy(optimization_config)
        optimization_config[config_dictionary.max_epoch] = 5
        train_rays = 1
        log.info("SMOKE TEST: 5 epochs, 1 ray, first 2 train sizes only.")

    n_groups = Scenario.get_number_of_heliostat_groups_from_hdf5(cfg.SCENARIO_PATH)

    # ------------------------------------------------------------------ sweep
    all_results: dict[int, dict] = {}

    with setup_distributed_environment(
        number_of_heliostat_groups=n_groups, device=device
    ) as ddp_setup:
        device = ddp_setup[config_dictionary.device]

        for train_size in train_sizes:
            log.info(f"\n{'='*60}")
            log.info(f"Train size: {train_size} / {train_sizes}")
            log.info(f"{'='*60}")

            train_map = [(hid, cal[:train_size], flux[:train_size]) for hid, cal, flux in full_train_map]
            subdir    = run_dir / f"train_size_{train_size}"

            if cfg.DATASET_TYPE == "synthetic":
                train_parser = SyntheticDatasetParser(_split_dir("train"))
                val_parser   = SyntheticDatasetParser(_split_dir("val"))
                test_parser  = SyntheticDatasetParser(_split_dir("test"))
            else:
                train_parser = PaintCalibrationDataParser(
                    sample_limit=train_size,
                    centroid_extraction_method=cfg.CENTROID_METHOD,
                )
                val_parser = PaintCalibrationDataParser(
                    sample_limit=cfg.VAL_SAMPLES,
                    centroid_extraction_method=cfg.CENTROID_METHOD,
                )
                test_parser = PaintCalibrationDataParser(
                    sample_limit=cfg.TEST_SAMPLES,
                    centroid_extraction_method=cfg.CENTROID_METHOD,
                )

            results = run(
                scenario_path=cfg.SCENARIO_PATH,
                device=device,
                ddp_setup=ddp_setup,
                train_mapping=train_map,
                val_mapping=val_map,
                test_mapping=test_map,
                train_parser=train_parser,
                val_parser=val_parser,
                test_parser=test_parser,
                optimization_config=optimization_config,
                output_dir=subdir,
                loss_type=cfg.LOSS_TYPE,
                dataset_type=cfg.DATASET_TYPE,
                n_surface_pts=cfg.SURFACE_POINTS_PER_FACET,
                train_rays=train_rays,
                perturbations=perturbations,
                heliostat_ids=[heliostat_id],
            )

            all_results[train_size] = results
            log.info(
                f"  train_size={train_size:3d} | "
                f"val: pre={results['pre_perturbation']['val']['mean_mrad']:.3f}  "
                f"pert={results['post_perturbation']['val']['mean_mrad']:.3f}  "
                f"trained={results['post_training']['val']['mean_mrad']:.3f}  | "
                f"test: trained={results['post_training']['test']['mean_mrad']:.3f} mrad  "
                f"({results['train_time_min']:.1f} min)"
            )

            _run_reporting(results, perturbations_json_data, [heliostat_id], subdir)

            gc.collect()
            torch.cuda.empty_cache()

    # ------------------------------------------------------------------ summary
    summary = {
        "heliostat_id": heliostat_id,
        "dataset_type": cfg.DATASET_TYPE,
        "loss_type":    cfg.LOSS_TYPE,
        "train_sizes":  train_sizes,
        "results":      {str(n): r for n, r in all_results.items()},
    }
    with open(run_dir / "summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    _plot_summary(summary, run_dir)
    _write_summary_table(summary, run_dir)

    log.info("\nAll sizes done:")
    log.info(f"  {'size':>5}  {'val pre':>8}  {'val pert':>9}  {'val trn':>8}  {'tst trn':>8}")
    for n in train_sizes:
        r = all_results[n]
        log.info(
            f"  {n:5d}  "
            f"{r['pre_perturbation']['val']['mean_mrad']:8.3f}  "
            f"{r['post_perturbation']['val']['mean_mrad']:9.3f}  "
            f"{r['post_training']['val']['mean_mrad']:8.3f}  "
            f"{r['post_training']['test']['mean_mrad']:8.3f}  mrad"
        )
    log.info(f"\nSummary table → {run_dir / 'summary_table.txt'}")
    log.info(f"Summary plot  → {run_dir / 'summary.png'}")
    log.info(f"Done. Results in: {run_dir}")


if __name__ == "__main__":
    main()
